run migrations modified

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -287,39 +287,75 @@ jobs:
 
   run-migrations:
     docker:
-      - image: circleci/node:13.8.0
-    steps:
+      - image: python:3.7-alpine3.11
+    steps:       
       - checkout
       - attach_workspace:
           at: .
       - restore_cache:
-          keys: [<< pipeline.id >>-backend-build]          
+          keys: [<< pipeline.id >>-backend-build]         
       - run:
-          name: Install AWS CLI dependencies
-          working_directory: /tmp
+          name: Install dependencies
           command: |
-            sudo apt-get update && sudo apt-get install -yy less
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
+              apk add --update ansible tar gzip ansible nodejs npm curl
+              pip install awscli
       - run:
           name: Run migrations
           working_directory: ./backend
           command: |
-            npm run migrations > migration_status
+            echo "BUILDING THE BACKEND ENVIRONMENT FILE FOR POSTGRES MIGRATIONS"
+            echo ENVIROMENT=production > .env
+            echo TYPEORM_CONNECTION=postgres >> .env
+            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> .env
+            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> .env
+            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> .env
+            echo TYPEORM_HOST=$TYPEORM_HOST >> .env
+            echo TYPEORM_PORT=$TYPEORM_PORT >> .env
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> .env
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> .env
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> .env
+            ls -latr
+            cat .env
+            echo "INSTALLING NPM MODULE DEPENDENCIES"
+            npm i > npminstall.log
+            echo "INSTALLING OATH-SIGN PACKAGE"
+            npm install oauth-sign >> npminstall.log
+            
+            echo "HOST: " $TYPEORM_HOST
+            echo "PWD: " $(pwd)
+            echo $TYPEORM_DATABASE
+            
+            npm run migrations:revert
+            echo "RUNNING POSTGRES DATABASE MIGRATIONS"
+            npm run migrations > migration.log
+            MIGRATION_LOG=/root/project/backend/migration.log
+            if test -f "$MIGRATION_LOG"; then
+                echo "$MIGRATION_LOG exists."
+            fi
+            echo "Output of the migration log"
+            cat migration.log
+
       - run:
           name: Send migration results to memstash
           working_directory: ./backend
           command: |
-            if grep -q "has been executed successfully" migration_status
-            then
-              echo "DB migration was successful, will update memstash..."
-              curl -H "Content-Type: text/plain" -H "token: 9a087c8d-59a3-475a-a1a1-915a0bf3c376" --request PUT --data "success" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
-            else
-              echo "DB migration failed, please verify setup! Probably the database already exists. Verify setup!"
-              curl -H "Content-Type: text/plain" -H "token: 9a087c8d-59a3-475a-a1a1-915a0bf3c376" --request PUT --data "failure" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
-            fi
-            echo "WorkflowID=${CIRCLE_WORKFLOW_ID}"
+              MIGRATION_LOG=/root/project/backend/migration.log
+              if test -f "$MIGRATION_LOG"; then
+                  echo "$MIGRATION_LOG exists."
+              fi
+              if grep -q "has been executed successfully" $MIGRATION_LOG; then
+                echo "SUCCESSFULLY EXECUTED THE DATABASE MIGRATIONS"
+                echo "Writing out to memstash : https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}"
+                curl -H "Content-Type: text/plain" -H "token: 9a087c8d-59a3-475a-a1a1-915a0bf3c376" --request PUT \
+                  --data "success" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+              else
+                echo "FAILED TO RUN THE DATABASE MIGRATIONS"
+                echo "Writing out to memstash : https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}"
+                curl -H "Content-Type: text/plain" -H "token: 9a087c8d-59a3-475a-a1a1-915a0bf3c376" --request PUT \
+                  --data "failure" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+                exit 1
+              fi
+              echo "WorkflowID=${CIRCLE_WORKFLOW_ID}"
       - revert-migrations:
           id: "${CIRCLE_WORKFLOW_ID}" 
           when: on_fail 
